// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TravelTourWebApp.Migrations
{
    [DbContext(typeof(TravelCompanyDbContext))]
    [Migration("20250718070022_FixRelationshipForHDV")]
    partial class FixRelationshipForHDV
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CongTyDuLich", b =>
                {
                    b.Property<string>("MaCTY")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCTY");

                    b.ToTable("CongTyDuLiches");
                });

            modelBuilder.Entity("HopDongChuyenDi", b =>
                {
                    b.Property<string>("MaHopDong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHDV1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHDV2")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTX")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaHDV1");

                    b.HasIndex("MaHDV2");

                    b.HasIndex("MaTX");

                    b.HasIndex("SoXe");

                    b.ToTable("HopDongChuyenDis");
                });

            modelBuilder.Entity("HuongDanVien", b =>
                {
                    b.Property<string>("MaHDV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("LuongNgay")
                        .HasColumnType("real");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoNgayLam")
                        .HasColumnType("int");

                    b.Property<string>("TenHDV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHDV");

                    b.ToTable("HuongDanViens");
                });

            modelBuilder.Entity("LichChay", b =>
                {
                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiemDi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiaVe")
                        .HasColumnType("real");

                    b.Property<string>("MaHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoKhachDi")
                        .HasColumnType("int");

                    b.Property<string>("SoXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Ngay");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("SoXe");

                    b.ToTable("LichChays");
                });

            modelBuilder.Entity("LoaiXe", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoGhe")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiXes");
                });

            modelBuilder.Entity("TaiXe", b =>
                {
                    b.Property<string>("MaTX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HeSoLuong")
                        .HasColumnType("real");

                    b.Property<float>("LuongCoBan")
                        .HasColumnType("real");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTX");

                    b.ToTable("TaiXes");
                });

            modelBuilder.Entity("XeDuLich", b =>
                {
                    b.Property<string>("SoXe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SoXe");

                    b.HasIndex("MaCTY");

                    b.HasIndex("MaLoai");

                    b.ToTable("XeDuLiches");
                });

            modelBuilder.Entity("HopDongChuyenDi", b =>
                {
                    b.HasOne("HuongDanVien", "HDV1")
                        .WithMany("HopDongs1")
                        .HasForeignKey("MaHDV1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HuongDanVien", "HDV2")
                        .WithMany("HopDongs2")
                        .HasForeignKey("MaHDV2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaiXe", "TaiXe")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaTX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XeDuLich", "XeDuLich")
                        .WithMany("HopDongs")
                        .HasForeignKey("SoXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HDV1");

                    b.Navigation("HDV2");

                    b.Navigation("TaiXe");

                    b.Navigation("XeDuLich");
                });

            modelBuilder.Entity("LichChay", b =>
                {
                    b.HasOne("HopDongChuyenDi", "HopDong")
                        .WithMany("LichChays")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XeDuLich", "XeDuLich")
                        .WithMany("LichChays")
                        .HasForeignKey("SoXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("XeDuLich");
                });

            modelBuilder.Entity("XeDuLich", b =>
                {
                    b.HasOne("CongTyDuLich", "CongTyDuLich")
                        .WithMany("XeDuLiches")
                        .HasForeignKey("MaCTY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoaiXe", "LoaiXe")
                        .WithMany("XeDuLiches")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongTyDuLich");

                    b.Navigation("LoaiXe");
                });

            modelBuilder.Entity("CongTyDuLich", b =>
                {
                    b.Navigation("XeDuLiches");
                });

            modelBuilder.Entity("HopDongChuyenDi", b =>
                {
                    b.Navigation("LichChays");
                });

            modelBuilder.Entity("HuongDanVien", b =>
                {
                    b.Navigation("HopDongs1");

                    b.Navigation("HopDongs2");
                });

            modelBuilder.Entity("LoaiXe", b =>
                {
                    b.Navigation("XeDuLiches");
                });

            modelBuilder.Entity("TaiXe", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("XeDuLich", b =>
                {
                    b.Navigation("HopDongs");

                    b.Navigation("LichChays");
                });
#pragma warning restore 612, 618
        }
    }
}
